[package]
name = "dec"
version = "0.1.0"
authors = ["'weather94' <'chlrltkd0@gmail.com'>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw0 = { path = "../cw0", version = "0.3.2" }
cw2 = { path = "../cw2", version = "0.3.2" }
cw20 = { path = "../cw20", version = "0.3.2" }
cosmwasm-std = { version = "0.12.0-alpha2", features = ["iterator"] }
cosmwasm-storage = { version = "0.12.0-alpha2", features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = { version = "0.12.0-alpha2" }
